import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import StoreProvider from '@/store/StoreProvider';
import ThemeProviderClient from '@/components/theme/ThemeProviderClient';
import ReactQueryProvider from '@/components/ReactQueryProvider';
import { Toaster } from '@/components/ui/toaster';
import { SocketProvider } from '@/components/SocketIoProvider';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Chat realtime',
  description: 'Generated by Võ Minh Phú',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased no-scrollbar`}>
        <ReactQueryProvider>
          <ThemeProviderClient>
            <StoreProvider>
              <SocketProvider>{children}</SocketProvider>
              <Toaster />
            </StoreProvider>
          </ThemeProviderClient>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
